# This is a AsciiDoctor workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push 
# events but only for the master branch
on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install AsciiDoctor
      run: |
        sudo apt-get install -y asciidoctor

    - name: Convert adoc files to HTML
      run: |
        find . -name "*.adoc" -exec asciidoctor {} \;

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: HTML files
        path: |
          **/*.html