# This is a AsciiDoctor workflow to help you get started with Actions
name: Build Asciidoc

on:
  push:
    branches: [ main ]
    paths:
    - '**.adoc'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install AsciiDoctor
      run: |
        sudo apt-get install -y asciidoctor

    - name: Convert adoc files to HTML
      run: |
        find . -name "*.adoc" -exec asciidoctor {} \;

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: html_artifacts
        path: |
          **/*.html