name: Build AsciiDoc to HTML and save as artifact

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build HTML
      run: |
        for file in **/*.adoc; do
          asciidoctor -r asciidoctor-diagram -b html5 -o "${file%.*}.html" "$file"
        done

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: html-artifact
        path: |
          **/*.html